name: home-ops

# Apps
include:
  - core/ddns-updater/ddns-updater.yml
  - core/database/database.yml
  - core/traefik/traefik.yml
  - core/watchtower/watchtower.yml
  - apps/adminer/adminer.yml
  - apps/roundcube/roundcube.yml
  - apps/ocis/ocis.yml
  - apps/website-aaronsoft/website-aaronsoft.yml
  - apps/website-get-orga-niced/website-get-orga-niced.yml

networks:
  # Public traffic (Traefik <-> Apps)
  traefik-public:
    name: traefik-public
    driver: bridge
    aliases:
      - ${OCIS_DOMAIN}

  # Secured Socket (Traefik <-> Socket Proxy)
  socket-internal:
    name: socket-internal
    internal: true

  # Database traffic (Apps <-> DBs) - Not exposed to Traefik
  db-internal:
    name: db-internal
    internal: true

  # Outbound API traffic (e.g., DDNS Updater)
  outbound-traffic:
    name: outbound-traffic
    driver: bridge