# --- Global Project Definition ---
name: home-ops

# --- Modular Service Includes ---
# Imports all standalone Docker Compose configurations into this master stack
include:
  # 1. Network & Routing Tier
  - core/routing/ddns-updater/ddns-updater.yml
  - core/routing/pihole/pihole.yml
  - core/routing/traefik/traefik.yml

  # 2. System & Maintenance Tier
  - core/system/fallback/fallback.yml
  - core/system/watchtower/watchtower.yml

  # 3. End-User Applications
  - apps/calibre/calibre.yml
  - apps/home-assistant/home-assistant.yml
  - apps/ocis/ocis.yml
  #  - apps/roundcube/roundcube.yml
  #  - apps/websites/web-hduong.yml
  - apps/immich/immich.yml

# --- Global Network Definitions ---
networks:
  # Connectivity: Outbound internet access for services requiring external APIs (e.g., Watchtower, DDNS)
  outbound-public:
    name: outbound-public
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.28.0.0/16
        - subnet: fd00:172:28::/64

  # Connectivity: Public traffic routing from the reverse proxy to exposed applications
  traefik-public:
    name: traefik-public
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.29.0.0/16
        - subnet: fd00:172:29::/64

  # Security: Highly restricted internal network strictly for Traefik to read the Docker socket via proxy
  socket-internal:
    name: socket-internal
    internal: true