services:
  # --- Init Service: Prepares the environment before the main application starts ---
  ddns-updater-init:
    extends:
      file: ../../../shared/templates.yml
      service: base-init
    container_name: ddns-updater-init

    # Execution: Fix permissions
    command: sh -c "chown -R ${DDNS_UPDATER_PUID:-1002}:${DDNS_UPDATER_GUID:-1002} /data"

    # State: Mount data directory
    volumes:
      - ./data:/data

  # --- Main Service: Handles the dynamic DNS updates ---
  ddns-updater:
    extends:
      file: ../../../shared/templates.yml
      service: base-secure
    image: qmcgaw/ddns-updater:${DDNS_UPDATER_DOCKER_TAG:-latest}
    container_name: ddns-updater

    # Security: Run as non-root user, lock the filesystem
    user: "${DDNS_UPDATER_PUID:-1002}:${DDNS_UPDATER_GUID:-1002}"
    read_only: true

    # Lifecycle: Wait for permissions to be fixed
    depends_on:
      ddns-updater-init:
        condition: service_completed_successfully

    # Connectivity: Attach to the shared outbound traffic
    networks:
      - outbound-public

    # Configuration: Global environment variables (Alphabetized)
    environment:
      CONFIG: '{"settings":[{"provider":"gandi","domain":"aaronsoft.de","ttl":10800,"ip_version":"ipv4","personal_access_token":"${GANDIV5_PERSONAL_ACCESS_TOKEN:?}"},{"provider":"gandi","domain":"get-orga-niced.de","ttl":10800,"ip_version":"ipv4","personal_access_token":"${GANDIV5_PERSONAL_ACCESS_TOKEN:?}"}]}'
      LOG_LEVEL: "info"
      RESOLVER_ADDRESS: "1.1.1.1:53"
      SERVER_ENABLED: "false"

    # State: Persistence to prevent API rate limiting from Gandi on container restart
    volumes:
      - ./data:/updater/data
    tmpfs:
      - /tmp


# --- Global Network Definitions ---
networks:
  outbound-public: