services:
  # --- Init Service: Prepares permissions for MariaDB ---
  mariadb-init:
    extends:
      file: ../../../shared/templates.yml
      service: base-init
    container_name: mariadb-init

    # Execution: Create directory and fix permissions
    command: sh -c "chown -R ${MARIADB_PUID:-1003}:${MARIADB_PGID:-1003} /data"

    # State: Mount database directory
    volumes:
      - ./data:/data

  # --- Database Service ---
  mariadb:
    extends:
      file: ../../../shared/templates.yml
      service: base-secure
    image: mariadb:${MARIADB_DOCKER_TAG:-11.4}
    container_name: mariadb

    # Security: Run as non-root user, lock filesystem
    user: "${MARIADB_PUID:-1003}:${MARIADB_PGID:-1003}"
    read_only: true

    # Lifecycle: Wait for permissions to be fixed
    depends_on:
      mariadb-init:
        condition: service_completed_successfully

    # Connectivity: Expose MariaDB on localhost only (required for home assistant), for internal access by other containers
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - mariadb-internal

    # Configuration: Natively auto-creates the databases and users on first startup (Alphabetized)
    environment:
      # Core Database Settings
      MARIADB_AUTO_UPGRADE: "true"
      MARIADB_BIND_ADDRESS: "0.0.0.0"
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD:?}"

      # App 1: Roundcube Variables
      HOMEASSISTANT_DB_NAME: "homeassistant"
      HOMEASSISTANT_DB_PASSWORD: "${HOMEASSISTANT_DB_PASSWORD:?}"
      HOMEASSISTANT_DB_USER: "homeassistant"

      # App 2: Roundcube Variables
      ROUNDCUBE_DB_NAME: "roundcubemail"
      ROUNDCUBE_DB_PASSWORD: "${ROUNDCUBE_DB_PASSWORD:?}"
      ROUNDCUBE_DB_USER: "roundcube"

      # App 3: OnlyOffice Variables
      ONLYOFFICE_DB_NAME: "onlyoffice"
      ONLYOFFICE_DB_PASSWORD: "${OCIS_ONLYOFFICE_DB_PASSWORD:?}"
      ONLYOFFICE_DB_USER: "onlyoffice"

    # State: Persistent data, initialization scripts, and temporary in-memory systems
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d:ro
    tmpfs:
      - /tmp
      - /run/mysqld

    # Monitoring: Built-in check to ensure the InnoDB engine is fully initialized
    healthcheck:
      test: "healthcheck.sh --connect --innodb_initialized"


# --- Global Network Definitions ---
networks:
  mariadb-internal: