services:
  # --- Init Service: Prepares the environment before the main application starts ---
  gandi-ddns-init:
    extends:
      file: ../templates.yml
      service: base-init
    container_name: gandi-ddns-init
    command: sh -c "chown -R ${PUID}:${GUID} /data"
    volumes:
      - ./data:/data

  # --- Main Service: Handles the dynamic DNS updates ---
  ddns-updater:
    extends:
      file: ../templates.yml
      service: base-secure
    image: qmcgaw/ddns-updater:${DDNS_UPDATER_VERSION_TAG}
    container_name: ddns-updater
    user: "${PUID}:${GUID}"

    # Connectivity: Attach to the shared outbound traffic
    networks:
      - outbound-public
    
    # Ensures permissions are fixed before the updater attempts to write to the volume
    depends_on:
      gandi-ddns-init:
        condition: service_completed_successfully

    # Configuration: Global environment variables
    environment:
      - LOG_LEVEL=info
      - SERVER_ENABLED=false
      - CONFIG={"settings":[{"provider":"gandi","domain":"aaronsoft.de","ttl":10800,"ip_version":"ipv4","personal_access_token":"${GANDIV5_PERSONAL_ACCESS_TOKEN}"},{"provider":"gandi","domain":"get-orga-niced.de","ttl":10800,"ip_version":"ipv4","personal_access_token":"${GANDIV5_PERSONAL_ACCESS_TOKEN}"}]}

    # State persistence to prevent API rate limiting from Gandi on container restart
    volumes:
      - ./data:/updater/data
    tmpfs:
      - /tmp

    # Security: Lock the filesystem
    read_only: true


# --- Global Network Definitions ---
networks:
  outbound-public: