# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Recorder: Use MariaDB for persistent state storage
recorder:
  db_url: !env_var HOMEASSISTANT_DB_URL

# Logger: Use environment variable to set log level
logger:
  default: !env_var HOMEASSISTANT_LOG_LEVEL