---
services:
  traefik:
    networks:
      traefik-public:
        aliases:
          - ${OCIS_ONLYOFFICE_DOMAIN:-onlyoffice.owncloud.test}

  collaboration-oo:
    image: owncloud/ocis:${OCIS_VERSION_TAG}
    networks:
      traefik-public:
    depends_on:
      ocis:
        condition: service_started
      onlyoffice:
        condition: service_healthy
    command: ["collaboration", "server"]
    environment:
      COLLABORATION_GRPC_ADDR: 0.0.0.0:9301
      COLLABORATION_HTTP_ADDR: 0.0.0.0:9300
      MICRO_REGISTRY: "nats-js-kv"
      MICRO_REGISTRY_ADDRESS: "ocis:9233"
      COLLABORATION_WOPI_SRC: http://collaboration-oo:9300
      COLLABORATION_APP_NAME: "OnlyOffice"
      COLLABORATION_APP_PRODUCT: "OnlyOffice"
      COLLABORATION_APP_ADDR: https://${OCIS_ONLYOFFICE_DOMAIN:-onlyoffice.owncloud.test}
      COLLABORATION_APP_ICON: https://${OCIS_ONLYOFFICE_DOMAIN:-onlyoffice.owncloud.test}/web-apps/apps/documenteditor/main/resources/img/favicon.ico
      COLLABORATION_APP_INSECURE: "true"
      COLLABORATION_CS3API_DATAGATEWAY_INSECURE: "true"
      COLLABORATION_LOG_LEVEL: info
      OCIS_URL: https://${OCIS_DOMAIN}
    volumes:
      # configure the .env file to use own paths instead of docker internal volumes
      - ${OCIS_CONFIG_DIR}:/etc/ocis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.collaboration-oo.entrypoints=http"
      - "traefik.http.routers.collaboration-oo.rule=Host(`collaboration-oo`)"
      - "traefik.http.routers.collaboration-oo.service=collaboration-oo"
      - "traefik.http.services.collaboration-oo.loadbalancer.server.port=9300"
    logging:
      driver: local
    restart: always

  onlyoffice:
    # note, you also need to add a volume when using the enterprise version, see below
    image: onlyoffice/documentserver:${OCIS_ONLYOFFICE_VERSION_TAG}
    networks:
      ocis-net:
    entrypoint:
      - /bin/sh
      - /entrypoint-override.sh
    environment:
      WOPI_ENABLED: "true"
      # self-signed certificates
      USE_UNAUTHORIZED_STORAGE: true
      JWT_ENABLED: false
      REDIS_SERVER_HOST: localhost
      REDIS_SERVER_PORT: 6379
    volumes:
      # paths are relative to the main compose file
      - ./config/onlyoffice/entrypoint-override.sh:/entrypoint-override.sh
      - ./config/onlyoffice/local.json:/etc/onlyoffice/documentserver/local.dist.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.onlyoffice.entrypoints=websecure"
      - "traefik.http.routers.onlyoffice.rule=Host(`${OCIS_ONLYOFFICE_DOMAIN:-onlyoffice.owncloud.test}`)"
      - "traefik.http.routers.onlyoffice.service=onlyoffice"
      - "traefik.http.services.onlyoffice.loadbalancer.server.port=80"
      # websockets can't be opened when this is omitted
      - "traefik.http.middlewares.onlyoffice.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.onlyoffice.middlewares=onlyoffice"
    logging:
      driver: local
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/hosting/discovery"]

# --- Global Network Definitions ---
networks:
  traefik-public: